"""Event-driven backtest engine and validation harnesses.

The engine processes one bar at a time. At each bar the engine snapshots the
portfolio's mark-to-market value, advances the cash and position accruals,
and applies any pending fills generated by the rebalance step on the prior
bar.
"""

from __future__ import annotations

from quantforge.backtest.cpcv import CombinatorialPurgedCV, cpcv_indices
from quantforge.backtest.engine import BacktestEngine, BacktestResult
from quantforge.backtest.portfolio_state import PortfolioState
from quantforge.backtest.walk_forward import walk_forward_splits

__all__ = [
    "BacktestEngine",
    "BacktestResult",
    "CombinatorialPurgedCV",
    "PortfolioState",
    "cpcv_indices",
    "walk_forward_splits",
]
